checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
tools:
    php_code_coverage: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests, config, docs]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests, config, docs]
build:
    environment:
        php:
            version: 5.6
    project_setup:
        before:
            - mysql -e "CREATE DATABASE test"
            - sudo composer self-update
            - composer --version
            - composer global require hirak/prestissimo --no-plugins
            - composer install --prefer-dist --no-interaction
    tests:
        override:
            -
                command: './vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
